# Generated by Django 4.2.2 on 2024-07-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('certifications', models.TextField(help_text='List of certifications')),
                ('experience_years', models.IntegerField(help_text='Number of years of experience')),
                ('specialties', models.TextField(help_text='Areas of specialty, e.g., weightlifting, yoga')),
                ('bio', models.TextField(help_text='Short biography of the trainer')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='trainer_pics/')),
                ('available', models.BooleanField(default=True, help_text='Is the trainer currently available for training?')),
            ],
        ),
    ]
