# Generated by Django 4.2.2 on 2024-06-05 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Master',
            fields=[
                ('User_Id', models.AutoField(primary_key=True, serialize=False)),
                ('User_Name', models.CharField(max_length=20)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=100)),
                ('Mobile', models.CharField(max_length=10)),
                ('Photo', models.ImageField(upload_to='Profile_Pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='User_Type',
            fields=[
                ('Type_Id', models.AutoField(primary_key=True, serialize=False)),
                ('User_Type', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='user_master',
            name='Type_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.user_type'),
        ),
    ]
