# Generated by Django 4.2.2 on 2024-07-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_user_master_user_type_delete_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='User_Master',
        ),
        migrations.DeleteModel(
            name='User_Type',
        ),
    ]
