# Generated by Django 4.2.2 on 2024-07-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_user_delete_user_master_delete_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
